"""Create audit_logs table

Revision ID: db206ecb39c4
Revises: 
Create Date: 2024-12-20 14:42:44.862338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db206ecb39c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('action_type', sa.String(length=50), nullable=True),
        sa.Column('resource_type', sa.String(length=50), nullable=True),
        sa.Column('resource_id', sa.String(length=100), nullable=True),
        sa.Column('result', sa.String(length=50), nullable=True),
        sa.Column('principal_type', sa.String(length=50), nullable=True),
        sa.Column('principal_authority', sa.String(length=100), nullable=True),
        sa.Column('principal_id', sa.String(length=100), nullable=True),
        sa.Column('request_id', sa.String(length=100), nullable=True),
        sa.Column('outcome_reason', sa.String(length=255), nullable=True),
        sa.Column('before', sa.String(length=255), nullable=True),
        sa.Column('after', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
